# ワークフローの名前
name: Deploy work flow for Amazon ECS

# mainブランチにマージしたときに実行
on:
  pull_request:
    branches:
      - main
    types: [closed]

# 環境変数の設定
env:
  AWS_REGION: ap-northeast-1
  ECS_WEBAPP_SERVICE: ecs-sample-webapp
  ECS_RESTAPI_SERVICE: ecs-sample-restapi
  WEBAPP_CONTAINER_NAME: ecs-sample-webapp
  BACKEND_CONTAINER_NAME: ecs-sample-backend
  RESTAPI_CONTAINER_NAME: ecs-sample-restapi
  WEBAPP_TAG: 1.0.1
  BACKEND_TAG: 1.0.0
  RESTAPI_TAG: 1.0.0
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

# ジョブの設定
jobs:
  deploy:
    # ジョブの名前
    name: deploy
    # イメージの指定
    runs-on: ubuntu-latest
    # タイムアウトの設定（永遠にクレジットを消費するのを防ぐため）
    timeout-minutes: 30

    # workflow内のリポジトリをコンテナ内にcheckout
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # AWSのシークレットアクセスキーを取得する
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    # ECRの認証情報を取得する
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    # webappのビルドとプッシュを行う
    - name: webapp push to ECR
      id: build-image-webapp
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd sample-webapp
        docker build -t $ECR_REGISTRY/$WEBAPP_CONTAINER_NAME:$WEBAPP_TAG .
        docker tag $ECR_REGISTRY/$WEBAPP_CONTAINER_NAME:$WEBAPP_TAG $ECR_REGISTRY/$WEBAPP_CONTAINER_NAME:latest
        docker push $ECR_REGISTRY/$WEBAPP_CONTAINER_NAME:$WEBAPP_TAG
        docker push $ECR_REGISTRY/$WEBAPP_CONTAINER_NAME:latest
    
    # backendのビルドとプッシュを行う
    - name: backend push to ECR
      id: build-image-backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd sample-backend
        docker build -t $ECR_REGISTRY/$BACKEND_CONTAINER_NAME:$BACKEND_TAG .
        docker tag $ECR_REGISTRY/$BACKEND_CONTAINER_NAME:$BACKEND_TAG $ECR_REGISTRY/$BACKEND_CONTAINER_NAME:latest
        docker push $ECR_REGISTRY/$BACKEND_CONTAINER_NAME:$BACKEND_TAG
        docker push $ECR_REGISTRY/$BACKEND_CONTAINER_NAME:latest

    # restapiのビルドとプッシュを行う
    - name: restapi push to ECR
      id: build-image-restapi
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd sample-restapi
        docker build -t $ECR_REGISTRY/$RESTAPI_CONTAINER_NAME:$RESTAPI_TAG .
        docker tag $ECR_REGISTRY/$RESTAPI_CONTAINER_NAME:$RESTAPI_TAG $ECR_REGISTRY/$RESTAPI_CONTAINER_NAME:latest
        docker push $ECR_REGISTRY/$RESTAPI_CONTAINER_NAME:$RESTAPI_TAG
        docker push $ECR_REGISTRY/$RESTAPI_CONTAINER_NAME:latest

    # webappサービスとrestapiサービスへの強制デプロイ
    - name: Deploy to ECS
      run: |
        aws ecs update-service --service $ECS_WEBAPP_SERVICE --cluster ecs-lesson-cluster --force-new-deployment
        aws ecs update-service --service $ECS_RESTAPI_SERVICE --cluster ecs-lesson-cluster --force-new-deployment

    # 成功時のメッセージ
    - name: Success
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_TITLE: Deploy flow / Success
        SLACK_COLOR: good
        SLACK_MESSAGE: Message for Success

    # 失敗時のメッセージ
    - name: Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_TITLE: Deploy flow / Failure
        SLACK_COLOR: danger
        SLACK_MESSAGE: Message for Failure

    # キャンセル時のメッセージ（タイムアウト時）
    - name: Cancel
      uses: rtCamp/action-slack-notify@v2.0.2
      if: cancelled()
      env:
        SLACK_TITLE: Deploy flow / Cancel
        SLACK_COLOR: danger
        SLACK_MESSAGE: Message for Cancel
